/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin.reports/index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminReportsReportIdRouteImport } from './routes/admin.reports/$reportId'
import { Route as AdminJobsPendingRouteImport } from './routes/admin.jobs/pending'
import { Route as AdminJobsHistoryRouteImport } from './routes/admin.jobs/history'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsReportIdRoute = AdminReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsPendingRoute = AdminJobsPendingRouteImport.update({
  id: '/jobs/pending',
  path: '/jobs/pending',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsHistoryRoute = AdminJobsHistoryRouteImport.update({
  id: '/jobs/history',
  path: '/jobs/history',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/jobs/history': typeof AdminJobsHistoryRoute
  '/admin/jobs/pending': typeof AdminJobsPendingRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/jobs/history': typeof AdminJobsHistoryRoute
  '/admin/jobs/pending': typeof AdminJobsPendingRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/jobs/history': typeof AdminJobsHistoryRoute
  '/admin/jobs/pending': typeof AdminJobsPendingRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/admin/jobs/history'
    | '/admin/jobs/pending'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/admin/jobs/'
    | '/admin/organizations/'
    | '/admin/reports/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/admin/jobs/history'
    | '/admin/jobs/pending'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/admin/jobs'
    | '/admin/organizations'
    | '/admin/reports'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/admin/jobs/history'
    | '/admin/jobs/pending'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/admin/jobs/'
    | '/admin/organizations/'
    | '/admin/reports/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/$reportId': {
      id: '/admin/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/admin/reports/$reportId'
      preLoaderRoute: typeof AdminReportsReportIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/pending': {
      id: '/admin/jobs/pending'
      path: '/jobs/pending'
      fullPath: '/admin/jobs/pending'
      preLoaderRoute: typeof AdminJobsPendingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/history': {
      id: '/admin/jobs/history'
      path: '/jobs/history'
      fullPath: '/admin/jobs/history'
      preLoaderRoute: typeof AdminJobsHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminJobsHistoryRoute: typeof AdminJobsHistoryRoute
  AdminJobsPendingRoute: typeof AdminJobsPendingRoute
  AdminReportsReportIdRoute: typeof AdminReportsReportIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminJobsHistoryRoute: AdminJobsHistoryRoute,
  AdminJobsPendingRoute: AdminJobsPendingRoute,
  AdminReportsReportIdRoute: AdminReportsReportIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
