/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedJobsRouteImport } from './routes/saved-jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'

const SavedJobsRoute = SavedJobsRouteImport.update({
  id: '/saved-jobs',
  path: '/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/home'
    | '/jobs'
    | '/login'
    | '/saved-jobs'
    | '/jobs/$jobId'
    | '/profile/edit'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/home'
    | '/jobs'
    | '/login'
    | '/saved-jobs'
    | '/jobs/$jobId'
    | '/profile/edit'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/home'
    | '/jobs'
    | '/login'
    | '/saved-jobs'
    | '/jobs/$jobId'
    | '/profile/edit'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SavedJobsRoute: typeof SavedJobsRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved-jobs': {
      id: '/saved-jobs'
      path: '/saved-jobs'
      fullPath: '/saved-jobs'
      preLoaderRoute: typeof SavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
  }
}

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  SavedJobsRoute: SavedJobsRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
