/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyJobsIndexRouteImport } from './routes/my-jobs/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as SettingsOrganizationRouteImport } from './routes/settings/organization'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as JobsNewRouteImport } from './routes/jobs/new'
import { Route as ApplicationsApplicationIdRouteImport } from './routes/applications/$applicationId'
import { Route as MyJobsJobIdEditRouteImport } from './routes/my-jobs/$jobId/edit'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJobsIndexRoute = MyJobsIndexRouteImport.update({
  id: '/my-jobs/',
  path: '/my-jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyJobsJobIdEditRoute = MyJobsJobIdEditRouteImport.update({
  id: '/my-jobs/$jobId/edit',
  path: '/my-jobs/$jobId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/my-jobs/': typeof MyJobsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/my-jobs/$jobId/edit': typeof MyJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/applications': typeof ApplicationsIndexRoute
  '/my-jobs': typeof MyJobsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/my-jobs/$jobId/edit': typeof MyJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/my-jobs/': typeof MyJobsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/my-jobs/$jobId/edit': typeof MyJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/interviews'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/applications/$applicationId'
    | '/jobs/new'
    | '/messages/$conversationId'
    | '/settings/organization'
    | '/applications/'
    | '/my-jobs/'
    | '/auth/google/callback'
    | '/my-jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/interviews'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/applications/$applicationId'
    | '/jobs/new'
    | '/messages/$conversationId'
    | '/settings/organization'
    | '/applications'
    | '/my-jobs'
    | '/auth/google/callback'
    | '/my-jobs/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/dashboard'
    | '/interviews'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/applications/$applicationId'
    | '/jobs/new'
    | '/messages/$conversationId'
    | '/settings/organization'
    | '/applications/'
    | '/my-jobs/'
    | '/auth/google/callback'
    | '/my-jobs/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  InterviewsRoute: typeof InterviewsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRoute
  JobsNewRoute: typeof JobsNewRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  MyJobsIndexRoute: typeof MyJobsIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  MyJobsJobIdEditRoute: typeof MyJobsJobIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-jobs/': {
      id: '/my-jobs/'
      path: '/my-jobs'
      fullPath: '/my-jobs/'
      preLoaderRoute: typeof MyJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId': {
      id: '/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-jobs/$jobId/edit': {
      id: '/my-jobs/$jobId/edit'
      path: '/my-jobs/$jobId/edit'
      fullPath: '/my-jobs/$jobId/edit'
      preLoaderRoute: typeof MyJobsJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  InterviewsRoute: InterviewsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRoute,
  JobsNewRoute: JobsNewRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  MyJobsIndexRoute: MyJobsIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  MyJobsJobIdEditRoute: MyJobsJobIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
