/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyJobsIndexRouteImport } from './routes/my-jobs/index'
import { Route as SettingsOrganizationRouteImport } from './routes/settings/organization'
import { Route as JobsNewRouteImport } from './routes/jobs/new'
import { Route as MyJobsJobIdEditRouteImport } from './routes/my-jobs/$jobId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJobsIndexRoute = MyJobsIndexRouteImport.update({
  id: '/my-jobs/',
  path: '/my-jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJobsJobIdEditRoute = MyJobsJobIdEditRouteImport.update({
  id: '/my-jobs/$jobId/edit',
  path: '/my-jobs/$jobId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/jobs/new': typeof JobsNewRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/my-jobs/': typeof MyJobsIndexRoute
  '/my-jobs/$jobId/edit': typeof MyJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/jobs/new': typeof JobsNewRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/my-jobs': typeof MyJobsIndexRoute
  '/my-jobs/$jobId/edit': typeof MyJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/jobs/new': typeof JobsNewRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/my-jobs/': typeof MyJobsIndexRoute
  '/my-jobs/$jobId/edit': typeof MyJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/jobs/new'
    | '/settings/organization'
    | '/my-jobs/'
    | '/my-jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/jobs/new'
    | '/settings/organization'
    | '/my-jobs'
    | '/my-jobs/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/jobs/new'
    | '/settings/organization'
    | '/my-jobs/'
    | '/my-jobs/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  JobsNewRoute: typeof JobsNewRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  MyJobsIndexRoute: typeof MyJobsIndexRoute
  MyJobsJobIdEditRoute: typeof MyJobsJobIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-jobs/': {
      id: '/my-jobs/'
      path: '/my-jobs'
      fullPath: '/my-jobs/'
      preLoaderRoute: typeof MyJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-jobs/$jobId/edit': {
      id: '/my-jobs/$jobId/edit'
      path: '/my-jobs/$jobId/edit'
      fullPath: '/my-jobs/$jobId/edit'
      preLoaderRoute: typeof MyJobsJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  JobsNewRoute: JobsNewRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  MyJobsIndexRoute: MyJobsIndexRoute,
  MyJobsJobIdEditRoute: MyJobsJobIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
